co30_Domination.Altis/x_client/x_f/x_ui/fn_adminspectate.sqf
co30_Domination.Altis/x_client/x_f/x_ui/fn_playerspectate.sqf

Fix for https://github.com/Xeno69/Domination/issues/11 , that should stop the log spam. Still wondering if nobody ever used admin spectate on Altis.

Quick fix for undefined var in sandstorm script

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/stringtable.xml
co30_Domination.Altis/x_server/x_f/fn_arifire.sqf

Allows repeated artillery calls.

added: new mission parameter to disable artillery cooldown (default 300 seconds)

---

co30_Domination.Altis/x_shc/x_f/fn_createmaintarget.sqf

fixed: civ kill score penalty was being applied to all players

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/stringtable.xml
co30_Domination.Altis/x_shc/x_shcinit.sqf

Parameter to disable spawning of enemy attack helis/jets

added: new parameter to disable enemy air attack

---

co30_Domination.Altis/description.ext

fixed: typo in property, modified the defaults if new features chosen

---

co30_Domination.Altis/x_client/x_f/fn_prespawned.sqf
co30_Domination.Altis/x_server/x_f/fn_handlescore.sqf

This fixes 1) and 2) from https://github.com/Xeno69/Domination/issues/46

Fixes for issue #46

---

co30_Domination.Altis/stringtable.xml

Update Simplified Chinese Translation

Update Simplified Chinese Translation

---

co30_Domination.Altis/scripts/fn_Zen_JBOY_UpDown.sqf

garrisoned infantry never stopped randomized up/down posture actions, note the up/down actions are still on eventhandler "firedNear" which is limited to 69m distance from the unit

fixed: updated up/down script by JohnnyBoy and Zenophon to v1.1

---

co30_Domination.Altis/revive/fn_addactions.sqf

added animations, checking for FAK or Medkit, better priority

tweaked revive addaction

---

co30_Domination.Altis/revive/fn_hasfak.sqf

added a new function revive/fn_hasfak.sqf

new function "fn_hasfak.sqf"

---

co30_Domination.Altis/server/fn_spawncrew.sqf

disableAI "RADIOPROTOCOL" for AI crew 

---

co30_Domination.Altis/server/fn_makemgroup.sqf

disableAI "RADIOPROTOCOL" for AI infantry groups

---

co30_Domination.Altis/stringtable.xml

Update Chinese Simplified

---

co30_Domination.Altis/stringtable.xml

Very small change.  I think the word "dashboard" is better than "status" for this.

fixed: changed Status to Dashboard

---

co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf

Very ugly while loop with no sleep.  My mistake.

HOTFIX - fixed: need a sleep, there is a way for continuous execution in a while{true} loop

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/fn_createinf.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

This gives another mission event for random selection (if mission events are enabled).  This mission is a simple hack of the sideprisoners side mission.  The enemy guards will shoot the prisoner if wounded.

Mission event captured pilot

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/common/fn_isbldghostile.sqf
co30_Domination.Altis/common/fn_isinhouse.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/stringtable.xml

added: fnc_inHouse position check now also checks several directions along the horizontal plane, some helper functions moved to separate files
fixed: event messages now appear correctly in multiplayer, better event messages

isInHouse improvements and mission event fixes

---

co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf

Quick fix for IFA3 guerrilla armor.

fixed: now using correct guerrilla armor for IFA3

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

added: parameter to enable simultaneous mission events in the maintarget area

---

co30_Domination.Altis/server/fn_createmaintarget.sqf

Minor fix.  The guerrilla tanks should be a rare event regardless if "event always" parameter is chosen.

fixed: 1 in 5 chance for the tank event to run

---

README.md

want a README?

---

co30_Domination.Altis/description.ext

fixed: moved fatigue and sway to top of parameters

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/stringtable.xml

fixed: moved AI settings higher in description.ext, minor typo

---

co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf

fixed: rescued pilots no longer crawl all the time and do not wander off when they join the players

---

co30_Domination.Altis/client/fn_dfps.sqf
co30_Domination.Altis/client/x_intro.sqf
co30_Domination.Altis/client/x_intro2.sqf
co30_Domination.Altis/client/x_setupplayer.sqf
co30_Domination.Altis/clientui/fn_updatesupportrsc.sqf

fixed: if the player selects "stream friendly UI" in Configure -> Game settings then Domination status bars are hidden

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

Added another maintarget event, guerrilla infantry with SAD waypoint in the maintarget.  Very messy fight.

Event guerrilla infantry incoming

---

co30_Domination.Altis/dlg/StatusDialog.hpp
co30_Domination.Altis/stringtable.xml

Can I remove the "fix headbug" button?

fixed: removed "fix headbug" button

---

co30_Domination.Altis/missions/events/fn_event_sideevac.sqf

fixed: pilots joining players was broken

---

Wiki_cfgparams_for_4_30.txt
co30_Domination.Altis/description.ext
co30_Domination.Altis/init/initcommon.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/stringtable.xml

event selection for three simultaneous random events, added very low/high to AI skill, proper cleanup for guerrilla infantry

Event selection fixes

---

co30_Domination.Altis/clientui/fn_statusdialoginit.sqf
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/dlg/StatusDialog.hpp
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf

I wanted to add maintarget event tasks to the dashboard.  I added the tasks to the secondary target list.  Is this ok?

added: maintarget event tasks added to dashboard

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf

messages were not being displayed, now works correctly on MP

fixed: forgot to sync event description variable

---

co30_Domination.Altis/client/x_setupplayer.sqf

Fixes #180 by using the correct event handler with ACE arsenal (basically fixing a typo).

Use correct event handler for ACE arsenal (fixes #180)

---

co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf

Being within 3m of the prisoner will cause him to instantly be rescued and disappear.

added: prisoner rescue only requires reaching the prisoner to instantly rescue

---

co30_Domination.Altis/missions/events/fn_event_sideevac.sqf

Being within 3m of the pilots will cause them to instantly be rescued and disappear.  Failure is only if both pilots are killed.  Success is considered by saving at least one pilot or at least one pilot surviving until the maintarget is complete.

added: pilot rescue only requires reaching the downed pilots to instantly rescue

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf

Fix for guerrillas still spawning too close sometimes.

fixed: min/max spawn radius for guerrilla infantry spawn to avoid creating guerrillas too close or too far from maintarget

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf

Sometimes seeing FPS drop during the guerrilla infantry event.  This might help.

fixed: added a sleep in a while loop guerrilla

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/common/fn_getbuildings.sqf
co30_Domination.Altis/common/fn_getcoveredpositions.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf

I refactored the building selection into a function so I can reuse it in some other code.  I also added a function to only select positions that are inside a building (a modification of a Killzone Kid script using lineIntersectsSurfaces).
No changes from the player perspective.

added: refactored building selection for garrisoned enemies, new helper getcoveredpositions

---

co30_Domination.Altis/init/d_allmen_B_default.sqf

now it include NATO woodcamo regulars and BLUFOR guerilla allies

expanded regular units spawnlist for blufor side

---

co30_Domination.Altis/init/d_allmen_G_default.sqf

expanded INDEP units spawnlist

---

co30_Domination.Altis/init/d_allmen_O_default.sqf

now it include Specnaz units (not a recon) and OPFOR guerilla allies

expanded regular units spawnlist for opfor side

---

co30_Domination.Altis/init/d_allmen_O_tanoa.sqf

now it include Specnaz units (not a recon) and OPFOR guerilla allies, also added missed heavy AT group

expanded regular units spawnlist for TANOA opfor side

---

co30_Domination.Altis/init/fn_preinit.sqf

now sniper teams has ghillie camo units

specops west and sniper teams opfor, blufor was expanded

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

dynamic number of guerrillas spawned, reduced the number of guerrilla tanks, tanks do not attack alone

Modify guerrilla units

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf

minor change, CAS should not trigger events

fixed: event triggers now have a defined height to prevent flyovers from triggering ground events

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/scripts/fn_moduleCAS.sqf

if artillery mission parameter is set to unlimited then CAS cooldown is 90 seconds

Cas and arty unlimited

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/common/fn_deletearrayunitsvehicles.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/stringtable.xml

added: new strings and notifications for explosives during missions or events, event cleanup now respects persistent corpse parameter, extracted cleanup into a function

prisoner event fixes, cleaned up the cleanup

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/init/d_compositions_default.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

yes/no parameter to disable the tripods of death

added: parameter to enable/disable static weapon defenses at maintarget

---

co30_Domination.Altis/stringtable.xml

Updated rus strings (stringtable.xml)

---

co30_Domination.Altis/stringtable.xml

added: some Spanish translations

---

co30_Domination.Altis/server/fn_civmodulekilleh.sqf

fixes a bug with civ kills and scoring

fixed: penalty for civilian kills by artillery or CAS

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/cfgfunctionscs.hpp
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

New event where one player tries to survive.  Currently set for 3 minutes to survive the attack.  Still no points to win but fun to play anyway.

all enemies attack one targeted player

---

co30_Domination.Altis/stringtable.xml

fixed: some English grammar corrections

---

co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/server/fn_serverinit.sqf

fixed: hostage event now is an exact marker location instead of an area search, pilots in rescue event given longer time with no damage, marked-for-death event is now enabled

hostage fixes and other stuff

---

co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf

fixed: wrong trigger dimensions

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

fixed: smaller event trigger areas, "all" events now also has guerrillas, fixed a string

minor event fixes

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

added: rescue event "kill the triggerman"
fixed: some event descriptions slow cleanup on dashboard, some event spawn locations were off by 10m

added: rescue event "kill the triggerman"

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/stringtable.xml

I made an attempt to assign points to the events.  Please feel free to change anything; these scores were only a guess.
This is using the simple kbTell, could be better with client side messages but functional.

added: scores awarded to players for completing maintarget events

---

co30_Domination.Altis/stringtable.xml

Update stringtable.xml - Add more JP translation

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/server/fn_createnexttarget.sqf
co30_Domination.Altis/stringtable.xml

added: new parameter to configure target radius
fixed: moved d_with_suppress higher in the parameter list
I'm having fun with large-sized maintarget + headless client.  So many bad guys.  The entire city is a fighting.  :)

added: new parameter to configure target radius

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_makegroup.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/stringtable.xml

added: parameters for number of patrol and guard/camps spawned, d_priority_target implemented for most infantry
fixed: "marked for death" survival event

additional logic and parameters to control number of guard and camp groups spawned, other fixes

---

co30_Domination.Altis/init/fn_preinit.sqf

fixed: TT Altis error with guerrilla units

---

co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

fixed: snipers were not being created with new dynamic parameter, tweaked the spawn factor variables, minor fix in HUD with duplicated character "Score::"

minor fixes

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_initvec.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/stringtable.xml

added: Squad Mgmt and Show Dashboard options added to flag and MHQ mousewheel menus
I still find many players that do not know how to use the Teamswitch key or somehow do not have the key configured.  Maybe this will help.

squad mgmt and dashboard menu actions

---

co30_Domination.Altis/client/fn_showdynamicgroupsdialog.sqf

fixed: forgotten file

---

README.md
co30_Domination.Altis/description.ext
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/stringtable.xml

added: parameter to disable voices, currently only works for VN map using their module
Sets disable voices to true by default on cam_lao_nam.

disable voices

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/bikb/kbinit.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_handleobservers.sqf
co30_Domination.Altis/server/fn_shootari.sqf
co30_Domination.Altis/stringtable.xml

more adaptive spawn settings, guerrilla map marker, audio warning if CAS/arty tell is enabled

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/scripts/fn_afterfirednear.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

added: civilians lay down when weapons are raised or fired nearby and return to raised positions after a quiet period

added civilian behaviors when threatened

---

co30_Domination.Altis/clientui/fn_pnselchanged.sqf

Hides player names when stream friendly UI is enabled.

added: stream friendly player names

---

co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf

fixed: use MPKilled with markedfordeath event

---

co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf

fixed: new event civ massacre description added to status dashboard

---

Wiki_cfgparams_for_4_56.txt
co30_Domination.Altis/client/fn_playerspawn.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/client/fn_vdhandler.sqf
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf

fixed: correct logic for automatic viewdistance default setting, dyke fix for SOG maps copied from johnnyboy, wiki params fix forcestream add autoviewdistance

fix for SOG, fix for default autoviewdistance setting

---

co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/stringtable.xml

added: server parameter to use faster intro sequence

---

co30_Domination.Altis/fsms/fn_HandleCamps2.fsm

added: faster camp capture (non-TT)

---

co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_serverinit.sqf

civ massacre happens too often, should be rare event to shock the players (3% chance now)

fixed: civ massacre event is very rare and with smaller trigger area

---

co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf

small fixes to the civ guerrilla event

Fix guerrilla civs

---

Wiki_cfgparams.txt

fixed: wiki param documentation

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/common/fn_ismissionobjective.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf

added: civilans are now created after the enemies, static civilians are not created near target objectives

do not spawn civs near objectives

---

co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

added: more civilian unit types

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_handleheal.sqf
co30_Domination.Altis/client/fn_handleunconscious.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/i_weapons_base.sqf

Add script to get points for stabilizing unconscious player.
Add splints and earplugs in the weapons_base script.
Changed the script for healing in ace with a PAK from using d_fnc_ascfc to using d_fnc_addscore.

Add ACE revive points, Add splints/earplugs to arsenal, Change some ACE heal script

---

co30_Domination.Altis/scripts/fn_moduleCAS.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_eachframe.sqf

CAS altitude to 1200m to avoid the ground.
Still crashing sometimes.

fixed: CAS at 1200m altitude

---

co30_Domination.Altis/scripts/fn_moduleCAS_bomb.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf

fixed: binoculars or laser will work for new CAS bomb

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_call_cas_bomb_napalm.sqf
co30_Domination.Altis/client/fn_playerspawn.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_bomb.sqf
co30_Domination.Altis/stringtable.xml

it is a very overpowered bomb but super fun to watch

added: player will see option in binoculars to drop 500 lb napalm bomb on SOG map

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_call_cas_bomb_napalm.sqf
co30_Domination.Altis/client/fn_playerspawn.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_bomb.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

enemy can be set as Opfor or Blufor mercenaries
nice guns but they don't wear the super 2035 body armor, easier kills

New parameter enemy mercenaries 2035 only

---

co30_Domination.Altis/client/fn_call_cas_bomb.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_bomb.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf

fixed: bomb correctly guided to terrain with laser or binoculars
added: if unlimited artillery is enabled then CAS bombs are dropped very quickly and without spawning a plane

fixed CAS bomb and added fast bomb drops

---

co30_Domination.Altis/common/fn_getfuzzyposition.sqf
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf

fixes in occupy script for civs
occupy script simpler forEach instead of for loop so script does not skip positions

fixed: simpler logic in occupyhouse script

---

co30_Domination.Altis/server/fn_createmaintarget.sqf

fixed: do not spawn guerrilla events if d_with_MainTargetEvents == -1

guerrillas spawning when they should not

---

co30_Domination.Altis/server/fn_createmaintarget.sqf

fixed some bad code, I used a variable before creating it

fixed: correctly create events variable

---

co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_garrisonUnits.sqf

sniper positions selected by a) highest sea level and b) position height is at least 2m over terrain height
minor change in the random position selection

Fix spawn locations

---

co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/server/fn_setupserver.sqf

some events were triggered by any d_own_side vehicles

fixed: UAV triggers MT events

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipescort.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_loop.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_garrisonUnits.sqf
co30_Domination.Altis/server/fn_makegroup.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

fixed: guerrillas shoot at blufor players
added: new VIP escort event

guerrillas fix and new VIP escort event

---

co30_Domination.Altis/init/fn_preinit.sqf

player can create a persistent UAV

added: players may create UAV at MHQ

---

Wiki_cfgparams.txt

added/updated a few missing parameters to the wiki

added: some updates to the wiki parameters file

---

Wiki_cfgparams.txt
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_deploy_mhq.sqf
co30_Domination.Altis/client/fn_makeuav_combat.sqf
co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/clientui/fn_initvecdialog.sqf
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/dlg/VecDialog.hpp
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/init/initcommon.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/server/fn_uav_loop.sqf
co30_Domination.Altis/stringtable.xml

added: create combat UAV at MHQ if d_extra_cas is enabled one per team, if d_arty_unlimited == 1 then one per player, cost of 30 points if ranked

create combat UAV

---

co30_Domination.Altis/description.ext

Fixed missing `$` on the `STR_DOM_MISSIONSTRING_2074` variables.

Fixed broken variables

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/revive/fn_uncon_oneframe.sqf

added a server param value to always autorevive

added: d_with_autorevive == 2 always autorevive

---

co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_loop.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/server/fn_target_clear.sqf

fixed: AI awareness behavior suddenly stopped when radiotower destroyed and d_mt_spotted is set to false

no AI awareness when radiotower is destroyed

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

added: play a sound when a "marked for death" event begins
fixed: civilians incorrectly placed in high positions
fixed: cleanup when some civilian units are abandoned near [0,0,0]

cleanup abandoned civs, other minor improvements

---

Wiki_cfgparams.txt
co30_Domination.Altis/description.ext
co30_Domination.Altis/server/fn_createambient.sqf
co30_Domination.Altis/server/fn_setenemymode.sqf
co30_Domination.Altis/server/fn_spawnvehicle.sqf
co30_Domination.Altis/stringtable.xml

added: "high" (4) armor setting to spawn more enemy tanks, APCs, etc (d_WithLessArmor)
added: server property d_noambient_bf_sounds_setting (same effect as the hidden DB setting d_noambient_bf_sounds)

high enemy armor count, no ambient battlefield sounds

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/common/fn_isflatempty.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/init/initcommon.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/server/fn_spawnvehicle.sqf
co30_Domination.Altis/server/fn_target_clear.sqf
co30_Domination.Altis/stringtable.xml

fixed: decreased AI skill for "very low" setting
added: isflatempty by Killzone_Kid moved to a function
added: civilian car position set with isflatempty for fewer explosions after spawn
added: separate server configurations to enable women military or civilians

fix civilian vehicles exploding and other stuff

---

co30_Domination.Altis/client/fn_makeuav_combat.sqf
co30_Domination.Altis/client/fn_uav_check.sqf

fixed: adjust viewdistance for cases where terminal stays connected (such as combat UAV)

combat UAV view distance fix

---

co30_Domination.Altis/stringtable.xml

Is this ok?
I don't want to be overly political but the original description makes me uncomfortable.

added: updated secondary description

---

co30_Domination.Altis/client/fn_headshot_notify.sqf
co30_Domination.Altis/server/fn_addheadshot.sqf

fixed: client may still show headshot icon when server is forced to no-HUD

server no-HUD and headshots

---

Wiki_cfgparams.txt
co30_Domination.Altis/changelog.txt
co30_Domination.Altis/client/fn_doarti.sqf

added: enemy arty chat message no-HUD support, wiki update, CL update

---

co30_Domination.Altis/client/fn_dfps.sqf
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipescort.sqf
co30_Domination.Altis/server/fn_dokbmsg.sqf
co30_Domination.Altis/server/fn_entitykilled.sqf
co30_Domination.Altis/server/fn_setupserver.sqf
co30_Domination.Altis/server/fn_spawnvehicle.sqf

fixed: client setting for isStreamFriendlyEnabled correctly hides the fps and local time widget

misc fixes

---

co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_createsecondary.sqf
co30_Domination.Altis/server/fn_dokbmsg.sqf
co30_Domination.Altis/server/fn_target_clear.sqf
co30_Domination.Altis/stringtable.xml

event spawn fixes
AT teams for every faction

preemptive event fixes

---

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_cleanerfnc.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_deleteempty.sqf
co30_Domination.Altis/server/fn_delstuff.sqf
co30_Domination.Altis/stringtable.xml

more small fixes, random spawn pos, now the mt cleaning function does not delete event units

Mt preemptive event more more

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_createsecondary.sqf
co30_Domination.Altis/stringtable.xml

added: pre-emptive event with some garrisoned guerrillas, new events server setting for "guerrilla and defense only"
fixed: better distances for pre-emptive events

pre-emptive event - guerrilla defense

---

co30_Domination.Altis/server/fn_createdrop.sqf

my last PR broke airdrop, steps were out of order

fix airdrop

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/client/fn_handleheal.sqf
co30_Domination.Altis/common/fn_isinhouse.sqf
co30_Domination.Altis/init/d_bldg_blacklist_common.sqf
co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf
co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/scripts/fn_afterfirednear_civ_global.sqf
co30_Domination.Altis/scripts/fn_unitgesture.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf
co30_Domination.Altis/server/fn_createdrop.sqf
co30_Domination.Altis/stringtable.xml

fixed civ spawn locations (now retries to find a good spawn location)
civs move away from nearby gunfire
non-player units will briefly stop moving when being healed

civ features, AI heal helper

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_createsecondary.sqf
co30_Domination.Altis/server/fn_endmaintarget.sqf
co30_Domination.Altis/server/fn_initvrespawn2.sqf
co30_Domination.Altis/server/fn_target_clear.sqf
co30_Domination.Altis/server/fn_targetclearm.sqf

fixed: do not use admin end maintarget function when a preemptive event is running
added: more logging for the mt create process

disable end maintarget button when preemptive event is running

---

co30_Domination.Altis/client/fn_makeuav_combat.sqf
co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf

this might fix the cleanup problem in the preemptive events

Minor event fixes preemptive

---

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/server/fn_delstuff.sqf

fixed: enemy cleanup broken when persistent corpses is enabled

---

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_makemgroup.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

added: maintarget event - rabbit rescue is back
fixed: adjusted group counts for guerrilla events
fixed: guerrillas as civilians have more random uniforms

rabbit rescue and small stuff

---

co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

fixed: sniper suppressive fire now targets a position instead of a player unit to prevent the target being "tracked by the unit dynamically" ie-- sniper shoots through walls at the player position, see doSuppressiveFire for details

sniper doSuppressiveFire shoots at player position through walls

---

co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf

fixed: event with guerrillas embedded as civs - guerrillas start with no weapons until triggered by firedNear 30m away

civ guerrillas improvements

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipescort.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

fixed: better success and failure messages for the VIP escort event
added: 2035 mercenaries are now available as Opfor enemies (appear as FIA infantry)
added: 2035 mercenaries now have some AA infantry
fixed: rabbit marker was not cleaning up after event ended

small fixes and improvements

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf

fixed: PiR mod needed more in cfgexec
fixed: don't force AI to shoot at UAV even when it is a valid target

more fixes for mod, project injury reaction

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf
co30_Domination.Altis/stringtable.xml

added: aggressive shooting - experimental, some enemy AI can be forced to fire their RPG launcher at players
fixed: small variation in direction of spawned civilian cars

AI shoot at players with RPG, experimental

---

co30_Domination.Altis/client/fn_createdomusermenu.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_createnexttarget.sqf

Fixes uav etc

---

co30_Domination.Altis/client/fn_weaponcargo.sqf
co30_Domination.Altis/clientui/fn_draw3dstuff.sqf

fixed: do not show virtual arsenal 3dmarker, flagpole beacon when streaming friendly or server-forced no-HUD

no-HUD stuff

---

co30_Domination.Altis/server/fn_civilianmodule.sqf

civ groups loop bug

---

dom_maker/make_dom.bat

remove pracs file in other versions
Add msara side missions to pracs-sahrani

Update make_dom.bat for PRACS

---

co30_Domination.Altis/server/fn_spawnvehicle.sqf

fixed: enemy vehicles sometimes fly through the air

---

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

fixed: when civs enabled, slightly fewer civ units in each group
fixed: missing parentheses

slightly fewer civ units, fix syntax

---

co30_Domination.Altis/description.ext
co30_Domination.Altis/i_server.sqf
co30_Domination.Altis/server/fn_make_isle_grp.sqf

added: server parameter "extra" isle defense includes AA if d_WithIsleDefense == 2

extra isle defense with AA

---

co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf
co30_Domination.Altis/server/fn_civilianmodule.sqf

fixed an undefined array related to some recent changes

fixed: undefined array for AAF as Indfor

---

co30_Domination.Altis/client/fn_setupplayer.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/stringtable.xml

added: server parameter to disable Domination weapon and inventory management

param to disable ptakeweapon

---

Wiki_cfgparams.txt
co30_Domination.Altis/init/d_veh_a_O_faction4-islamicstate.sqf
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf

added: faction Islamic State updated vehicles, updated infantry AT
added: force RPG fire script improved, now creates incoming rocket with fn_moduleCAS_guidedmissile

RPG script misc

---

README.md
Wiki_cfgparams.txt
co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf
co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/stringtable.xml

fixed: RPG script do not broadcast setVariable
fixed: minor wiki updates

small fixes

---

co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf

RPG can fly over the players' head on a proper ballistic flight path.

improved rpg flight path, civ cars

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/d_init.sqf
co30_Domination.Altis/description.ext
co30_Domination.Altis/init/d_bldg_blacklist_common.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf
co30_Domination.Altis/server/fn_civiliancars.sqf
co30_Domination.Altis/server/fn_createdrop.sqf
co30_Domination.Altis/stringtable.xml

a mix of stuff, mostly fixes
force RPG is very smooth now, lots of fun

Force rpg rabbit and fixes

---

co30_Domination.Altis/bikb/domkba3.bikb
co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/description.ext
co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf
co30_Domination.Altis/missions/events/fn_event_infantry_ambush.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipescort.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf
co30_Domination.Altis/server/fn_getunitlistm.sqf
co30_Domination.Altis/server/fn_serverinit.sqf
co30_Domination.Altis/stringtable.xml

fixed: minor group size override bug
added: d_grp_size_override 2 or above to set max group size
added: new maintarget event infantry ambush

ambush event and group size override fix

---

co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf
co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf
co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf
co30_Domination.Altis/missions/events/fn_event_infantry_ambush.sqf
co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf
co30_Domination.Altis/missions/events/fn_event_rabbitrescue.sqf
co30_Domination.Altis/missions/events/fn_event_sideevac.sqf
co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf
co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
co30_Domination.Altis/missions/events/fn_event_sidevipescort.sqf
co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf
co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf

small stuff

---

co30_Domination.Altis/cfgfunctions.hpp
co30_Domination.Altis/init/fn_preinit.sqf
co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile.sqf
co30_Domination.Altis/scripts/fn_moduleCAS_guidedmissile2.sqf
co30_Domination.Altis/server/fn_createmaintarget.sqf

here are a few bug fixes that would be nice to merge into the master branch

fixes for laser guided bomb, extra overwatch group, some faction fixes

---

co30_Domination.Altis/scripts/fn_force_fire_rpg.sqf

Fixes the AI stutter.
The unit shoots the RPG instantly so it is less realistic but also less complex.

fixed: simplified enemy RPG force fire script to avoid stuttering
