Xeno69/Domination

co30_Domination.Altis/x_client/x_f/fn_handleheal.sqf, co30_Domination.Altis/x_client/x_setupplayer.sqf
This adds support for ranked medic points when ACE is enabled.
It is not only possible to distribute points in correlation to the used medical item, it is also possible to differentiate between soldiers and ACE medics/doctors, which have their very own points distribution.
To change the distribution, simply add cases to the switch statement with the corresponding ACE medic actions and change points.
=> ACE support for medic points in ranked version

co30_Domination.Altis/x_missions/common/fn_sideelimofficer.sqf
_fortress variable was encapsulated inside if statement despite being used outside.
=> Fixed encapsulated _fortress variable

co30_Domination.Altis/description.ext, co30_Domination.Altis/stringtable.xml, co30_Domination.Altis/x_bikb/domkba3.bikb, co30_Domination.Altis/x_shc/x_f/fn_createmaintarget.sqf
Added functionality to create civilian modules and configure properties related to civ handlers.  Killing a civilian can penalize the player (decrease player score) according to configuration.  Killing a civ is announced via side chat.
There is no cleanup for the spawned civ modules.  One civ module is spawned upon target init but is not yet cleaned up during target teardown.
=> Civilians on targets

co30_Domination.Altis/x_missions/x_missionssetup.sqf
As this feature did cost me quite a few minutes of my time to debug, a little clarification on how to properly implement custom bonusvecs in sidemissions.
Without those extra lines it won't work on HCs, since the variable won't get passed on to the server
=> Clarification on custom bonusvec code on HC (only comment)

co30_Domination.Altis/description.ext, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/server/fn_civmodulekilleh.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_createsecondary.sqf
* shorter field names
* modified civilian unit count parameter minimum to 10 since any value less than 10 is invalid and ignored by the Arma engine
* modified default civilian group count from 4 to 2 (too many civilians by default)
=> fixed: shorter field names

co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/stringtable.xml
Submitting again with my proper Github login.
Parameterized radius, can create enemy units with a chosen placement radius. Ambush groups that are outside the main target can act as quick reaction to fighting in town. Creates some interesting fights and sniper angles. Defaults are not changed; this pull request does not change the default experience.
=> added: parameters for enemy spawn radius

co30_Domination.Altis/description.ext, co30_Domination.Altis/init/initcommon.sqf, co30_Domination.Altis/server/fn_createsecondary.sqf, co30_Domination.Altis/stringtable.xml
This fixes a small bug in the number of created camps where 5 was ambiguous (either 5 or -1).
I also decided to remove the new "random/maximum" parameter since this is simpler.  The default behavior has not changed (creates 3 to 5 camps by default).
=> fixed: d_max_camp_cnt logic and parameter fix

co30_Domination.Altis/description.ext, co30_Domination.Altis/init/fn_preinit.sqf, co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf
added: parameter option for very low number of civilian vehicles better for very small villages, civilian vehicles are now determined by which map is selected (no more shiny sports cars in villages), civilians unit models are now determined by which map is selected, civilians now have randomized faces grouped by head type
fixed: civilians now have a smaller spawn and movement radius to wander less, ammo check loop now accounts for magazine reload
=> civilian unit types, faces, and vehicles now determined by which map is being played, other minor fixes

co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
Fixes the wave of enemies upon initial contact.  Enemy bots were firing and triggering all ambush groups in the entire target area within the first minute of combat.
=> fixed: ambush group movement now only triggered if firedNear firer is an enemy

co30_Domination.Altis/description.ext, co30_Domination.Altis/scripts/fn_createsimpleobject.sqf, co30_Domination.Altis/scripts/fn_objectsmapper.sqf, co30_Domination.Altis/stringtable.xml
added: parameter to toggle creating camps with createVehicle vs createSimpleObject to allow penetration and damage of camp objects
The parameter default matches to current default with simulation disabled.  The current camps look very cool but it breaks immersion to see rocket hit an Ifrit and see no damage or see bullets stopped by a camo net.  I would like this parameter enabled by default but it depends on your preference for network efficiency.  :)
=> parameter to allow camps to simulate penetration and damage

co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf, co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf, co30_Domination.Altis/missions/fn_createinf.sqf, co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf, co30_Domination.Altis/server/fn_makemgroup.sqf, co30_Domination.Altis/stringtable.xml
Tank event now has mixed armor units.
Also added a parameter for createinf and makemgroup to allow the exact number of units to be set (not random).
=> fixed: missing semicolon was causing the guerrilla tanks event to fail, minor changes to event descriptions

co30_Domination.Altis/dlg/StatusDialog.hpp
Larger text in dashboard dialog.  I have difficulty reading some text in Domination with the current size.
What do you think?
4K
1080
=> fixed: StatusDialog.hpp larger text for status boxes on the left side

co30_Domination.Altis/clientui/fn_statusdialoginit.sqf, co30_Domination.Altis/dlg/StatusDialog.hpp
I'm trying to hide some of the dialog elements when those elements are not relevant (ie-- ranking information when d_with_ranked is false) so I created some arbitrary IDs so they can be hidden with ctrlShow.
=> added: some status dialog items are hidden if not relevant to mission parameters

co30_Domination.Altis/client/fn_inventoryopened.sqf, co30_Domination.Altis/client/x_setupplayer.sqf
When merged, this commit will allow ACE arsenal to be used only if ACE is present and "Use only mod weapons in Virtual Arsenal" is false.
=> Allow ACE arsenal if arsenal restrictions are disabled

co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_makegroup.sqf, co30_Domination.Altis/server/fn_makemgroup.sqf, co30_Domination.Altis/server/fn_spawncrew.sqf, co30_Domination.Altis/server/fn_target_clear.sqf, co30_Domination.Altis/stringtable.xml
This pull request adds support for corpses to remain on the ground where they fall until the maintarget is cleared.  This adds a very dark but interesting visual after an extended firefight...
This seems to have only minor performance impact on the server, perhaps more performance impact on the client.  I think the visual improvement to the environment is worth it however.  Very interesting when you walk through areas more than one time.
The implementation adds parameters to d_fnc_makemgroup signature and should be backward compatible.  This can support sidemissions but I could not think of a variable to while watch for sidemissions, maintarget has d_mt_done but nothing for sidemissions... perhaps if we can determine an easy way to trigger a cleanup then it can be added to side missions …
=> added: maintarget AI leave persistent corpses until the target is cleared, not implemented for sidemissions yet

co30_Domination.Altis/clientui/fn_glselchanged.sqf, co30_Domination.Altis/clientui/fn_statusdialoginit.sqf
Additional choices in Domination dashboard for setTerrainGrid to use the available higher quality grass settings 6.25 / 3.125.
=> added: two new grass settings can now select: none / medium / full / high / very high

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf
The guerrilla spawn position was being calculated by finding the midpoint between the maintarget and the nearest location.  Sometimes that was too close to the maintarget so if midpoint is less than 375m then just use position of the nearest location and ignore midpoint calculation.
=> fixed: guerrilla infantry sometimes spawned too close to maintarget

co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_shootari.sqf, co30_Domination.Altis/stringtable.xml
Alert players to enemy artillery without the intel requirement.
=> added: parameter to announce enemy artillery or CAS without capturing intel

co30_Domination.Altis/server/fn_civilianmodule.sqf
This is a minor fix to the civilian module spawning.
In the future I may rewrite the code to directly create simple agent civilians.  I don't like the civilian module much... the behavior is ridiculous and they always walk around the warzone like they are on a vacation.
=> fixed: bug was not using unique group for each civ module created

co30_Domination.Altis/init/fn_preinit.sqf
When merged, this PR will change the CUP BLUFOR air taxi aircraft from just the MV-22 Osprey to a selection of the UH-60M Blackhawk, CH-47F Chinook, or the MH-6J Littlebird. This is done to resolve the issues with the AI landing VTOL aircraft like the Osprey - currently, the air taxi fails 9 times out of 10.
=> Fix CUP BLUFOR air taxis by using different aircraft

.gitignore
When merged, this PR will add mikero's depbo64.dll to .gitignore. This is done to keep git changes clean since dom_maker requires this file to be present but we don't want to accidently commit it to the repo.
=> Ignore mikero's depbo64.dll

co30_Domination.Altis/client/fn_dfps.sqf, co30_Domination.Altis/client/x_intro.sqf, co30_Domination.Altis/client/x_intro2.sqf, co30_Domination.Altis/client/x_setupplayer.sqf, co30_Domination.Altis/clientui/fn_updatesupportrsc.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/stringtable.xml
Can I try to submit this again?
The client can still choose isStreamFriendly but I would like to add a parameter so the server can force that setting.  It would be nice to be able to provide a consistent user experience and many players don't know about the client setting.
=> Force streamfriendlyui

co30_Domination.Altis/server/fn_handleobservers.sqf
I copied the same notification logic used in fn_shootari.sqf so now notifies when CAS is called.
I am not certain if I am checking the correct intel for CAS notification but I tried this one:
d_searchintel # 1
Please fix if it is incorrect.
=> fixed: notify players when CAS is called if team obtained intel or if "always tell" mission parameter is true

co30_Domination.Altis/clientui/fn_statusdialoginit.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf
fixed the line breaks on dashboard when events were enabled
secondary objective prefix is "***" and event objective is "!!!"
=> fixed: incorrect logic in maintarget event selection, improved dashboard list and line breaks

README.md, co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/common/fn_getbuildings.sqf, co30_Domination.Altis/common/fn_isinhouse.sqf, co30_Domination.Altis/common/fn_isvisible.sqf, co30_Domination.Altis/common/fn_sortarraybydistance.sqf, co30_Domination.Altis/missions/events/fn_event_sideevac.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf, co30_Domination.Altis/missions/fn_createinf.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_makemgroup.sqf
* added a "dry run" parameter to the occupy script so we can test if a building has the required filtered positions before moving any units
* extracted some helper functions
* prisoner rescue event now has a suicide bomb
* prison guards now wear unusual headgear to help players identify them
=> Maintarget event fixes

co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/init/d_compositions_default.sqf, co30_Domination.Altis/init/initcommon.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/stringtable.xml
This provides a way to load mission parameters for people (like me) who do not use an external database.  Requires -filePatching enabled on server.  The file contents are compiled.
example domination.cfg file:
d_enablefatigue=0;
d_enablesway=0;
Parameters will show default setting for fatigue and sway but when mission starts the value from the text file will be used.
=> optionally load and compile from a text file "domination.cfg" in Arma server root dir

co30_Domination.Altis/description.ext
now the weather and time modules work in zeus with strict cfgremoteexec security
=> fixed: whitelisted weather and skip time functions required for the respective zeus modules to work

co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf
The overwatch units are too easy to shoot in the back.  This will allow them to move a bit when the players are firing nearby and make house clearing more dynamic.
=> added: overwatch units are allowed to move when an enemy fires a weapon nearby

co30_Domination.Altis/server/fn_handleobservers.sqf
fixed: when AI awareness parameter is enabled enemy artillery observers now only call a strike if a player is visible (line-of-sight) to prevent artillery spam due to awareness script "reveal 4" on player units
=> fix awareness script and artillery observers

co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/client/fn_iseligibletospawnnewunit.sqf, co30_Domination.Altis/clientui/fn_beam_tele.sqf, co30_Domination.Altis/clientui/fn_respawn_mar_anim.sqf, co30_Domination.Altis/clientui/fn_teleportdialoginit.sqf, co30_Domination.Altis/clientui/fn_teleupdate_dlg.sqf, co30_Domination.Altis/clientui/fn_update_telerespsel.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/revive/fn_buttonclickrespawn.sqf, co30_Domination.Altis/stringtable.xml
added: new selection for d_respawnatsql allows players to spawn on squad leader or any living squad member, iseligibletospawnnewunit long name but useful utility function
Tested on MP with two separate machines.  Respawn button enabled for the Squad leader if any squad member is alive.  Helps avoid the entire team being wiped out.
=> spawn on squad leader or squad member

co30_Domination.Altis/description.ext, co30_Domination.Altis/init/fn_preinit.sqf
added: server admin can set a default value for client side checkbox"automatically reduce view distance at maintarget" still false for TT and true otherwise
not sure if you will like this change, normally this is a client-side setting but I would like to "force" a default on the server (but user can still change it as usual)
=> default value for auto viewdistance

co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_markedfordeath.sqf, co30_Domination.Altis/missions/events/fn_event_sideevac.sqf, co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf, co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf
added: random maintarget event trigger locations are relative to d_cur_target_radius
supports larger target radius so events are properly spread out
=> event trigger locations are relative to the radius of the current target

co30_Domination.Altis/client/fn_setupplayer.sqf
This is a follow-up for #325 .  The names were only hidden after a player toggled the pnselchanged so here I'm trying to init with the correct state (no huddo).
=> fixed: do not init player names if stream friendly ui is enabled

co30_Domination.Altis/bikb/domkba3.bikb, co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf, co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_serverinit.sqf, co30_Domination.Altis/stringtable.xml
added: new event - stop civilian massacre, available when awareness or aggressiveshoot is enabled and civilians are present
=> new event - stop civilian massacre

co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_createmaintarget.sqf
high CPU events are now under "with guerrillas" selection, helps low CPU servers avoid events that cause lag
=> Only run civ event when guerrillas enabled

co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/missions/events/fn_event_civ_massacre.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_createsecondary.sqf, co30_Domination.Altis/server/fn_serverinit.sqf
an ugly solution, civilians are spawned before objectives so just delete the civs that are too close to radiotower/vehicle HQ
=> Civs removed near mt objectives

co30_Domination.Altis/revive/fn_buttonclickrespawn.sqf
changes the default respawn position so it is not directly in the squad leader's line of fire
=> added: respawn teammates 1m behind squad leader position to avoid friendly fire

Wiki_cfgparams.txt, co30_Domination.Altis/common/fn_getbldgswithpositions.sqf, co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf, co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf, co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/scripts/fn_afterfirednear.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_garrisonUnits.sqf, co30_Domination.Altis/server/fn_getunitlistm.sqf, co30_Domination.Altis/server/fn_makegroup.sqf, co30_Domination.Altis/server/fn_makemgroup.sqf, co30_Domination.Altis/stringtable.xml
added: better logic to determine the number of spawned enemy and civ units, enforce sane limits
changes civ spawn locations, not using the "covered positions" function
added a blacklist for buildings that should not be used for civilians, useful in SOG maps (dyke objects are incorrectly considered buildings)
=> calculate enemies and civ counts

Wiki_cfgparams.txt, co30_Domination.Altis/bikb/domkba3.bikb, co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_addheadshot.sqf, co30_Domination.Altis/server/fn_entitykilled.sqf, co30_Domination.Altis/stringtable.xml
added: mission parameter to show player headshots and distance in side chat
d_show_headshots default 0 is current behavior with no headshot indicator
d_show_headshots 1 will show icon client side only (quickly fading skull and number of meters?  not yet implemented)
d_show_headshots 2 shows client and server via side chat
=> show headshot details in side chat

co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_garrisonUnits.sqf, co30_Domination.Altis/server/fn_target_clear.sqf
fixed: ambush and overwatch units are now allowed to move once injured via a hit event handler, spawning enemies in top floor building positions does not work correctly so it is now disabled in fn_garrisonUnits.sqf until fixed, added more buildings to the spawn blacklist, keep a global list of building positions used for civilian spawns to avoid spawning civ agents on top of each other
=> allow static units to move if injured, enemies now spawn on the top floor more often, civilian fixes

co30_Domination.Altis/scripts/fn_moduleCAS.sqf, co30_Domination.Altis/scripts/fn_moduleCASAI.sqf
Possible solution to CAS crashing when the flight lags.
Pros:  CAS vehicle does not crash when flight path is laggy.
Cons: the higher altitude might be max viewdistance for some players so they will only hear the A10.
=> fixed: airstrike with steeper angle of attack and high altitude

co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/client/fn_call_cas_bomb_napalm.sqf, co30_Domination.Altis/client/fn_playerspawn.sqf, co30_Domination.Altis/client/fn_setupplayer.sqf, co30_Domination.Altis/scripts/fn_moduleCAS_bomb.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/stringtable.xml
I am still trying to prevent civilians from being near the maintarget objectives but they are sneaky.
This is intended to avoid penalizing players who blow up radiotowers, barracks etc where civilians will not move.
=> Civilian near objectives penalty workaround

co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/common/fn_getfuzzyposition.sqf, co30_Domination.Altis/missions/common/fn_sidecache.sqf, co30_Domination.Altis/missions/events/fn_event_guerrillas_embedded_as_civilians.sqf, co30_Domination.Altis/missions/events/fn_event_sideevac.sqf, co30_Domination.Altis/missions/events/fn_event_sidekilltriggerman.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisonerdefuse.sqf, co30_Domination.Altis/missions/events/fn_event_sideprisoners.sqf, co30_Domination.Altis/missions/events/fn_event_sidevipdefend.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_global.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_garrisonUnits.sqf, co30_Domination.Altis/server/fn_makenewtower.sqf, co30_Domination.Altis/server/fn_serverinit.sqf
added: civilians spawned with occupy script can be on upper floors
added: occupy script uses fuzzy positions when build positions are full
fixed: occupy script places all units in a group and does not delete units
fixed: occupy script should not use -1 radius
fixed: snipers do not spawn on roof
=> occupy script improvements and fixes

co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_initvrespawn2.sqf, co30_Domination.Altis/server/fn_vrespawn2.sqf
I wasn't using d_fnc_getbuildings to place civilians, now it checks for enemies before spawning
also removed some noisy logs
=> fixed: do not spawn civilians near enemy units

co30_Domination.Altis/common/fn_getbldgswithpositions.sqf, co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/stringtable.xml
fixed: enemy unit placement now uses same blacklist for buildings as the civilian units
added: some bad buildings to the blacklist (container buildings with no doors)
=> fixed: use building blacklist for enemy units as well as civilians

co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/stringtable.xml
fixed: some maintarget events (guerrillas and defense events) should only be available when configured in settings
=> only create defense and guerrilla events when d_with_MainTargetEvents is configured -3 or -4

Wiki_cfgparams.txt
If you'd like to see the rendered result, I've added a wiki page in my fork of the domination repo which you can view [here](https://github.com/PurplProto/Domination/wiki/Params).
The motivation behind this PR is that I found a few parameters listed with incorrect values, so I wrote a quick script to parse the `description.ext` and substitute all the variables there with the values from `stringtable.xml`. If you'd like to use the script in the future, feel free to do so. I've made it publicly available [here](https://github.com/PurplProto/Xeno69-Domination-params-parser).
It might also be worth noting where there were multiple default values depending on the mission, I took the ones in the `__ALTIS__` conditional block.
=> Update Params wiki page

Wiki_cfgparams.txt
Updated the script to build the param table to output the params in a format close to what the params wiki page used to be like. An example can be seen [here](https://github.com/PurplProto/Domination/wiki/Params/9b33748427e6f261b7ca3681b987086c35629f15).
=> Convert params table to previous formatting

co30_Domination.Altis/server/fn_civiliancars.sqf, co30_Domination.Altis/server/fn_spawnvehicle.sqf
fixed: spawn vehicle should gracefully fail if flat position cannot be found with 99 attempts (just don't create the vehicle at all)
=> vehicle find position can cause maintarget setup the fail

co30_Domination.Altis/bikb/domkba3.bikb, co30_Domination.Altis/cfgfunctions.hpp, co30_Domination.Altis/clientui/fn_checkpjumppos.sqf, co30_Domination.Altis/clientui/fn_mapondraw.sqf, co30_Domination.Altis/d_init.sqf, co30_Domination.Altis/init/fn_preinit.sqf, co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_tanksincoming.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_createsecondary.sqf, co30_Domination.Altis/server/fn_delstuff.sqf, co30_Domination.Altis/server/fn_makenewtower.sqf, co30_Domination.Altis/server/fn_setenemymode.sqf, co30_Domination.Altis/server/fn_target_clear.sqf, co30_Domination.Altis/stringtable.xml
new events will be available if the server is configured for "events with guerrilas"
a preemptive event may be randomly selected (10% chance) then 50/50 chance the event will be a) opfor vs indfor or b) opfor only
if preemptive event is selected:
* do not create enemies inside the maintarget 
* create tower and hq camps but no units or vehicles
* start event - create opfor units and vehicles in a nearby location
* start event - existing guerrila event in nearby location at opposite side of maintarget
* opfor and indfor will wait for 60 seconds and then march into town and fight each other
* players may parajump in the target during this event
* victory condition for mt_done is forced to "low AI" so players must clear out the enemy
=> new "preemptive" event type and events

Wiki_cfgparams.txt, co30_Domination.Altis/client/fn_bike.sqf, co30_Domination.Altis/client/fn_makeuav_combat.sqf, co30_Domination.Altis/client/fn_pjump.sqf, co30_Domination.Altis/clientui/fn_checkpjumppos.sqf, co30_Domination.Altis/description.ext, co30_Domination.Altis/init/fn_preinit.sqf, co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createdrop.sqf, co30_Domination.Altis/stringtable.xml
added: CUP Takistan civilians
fixed: walking civilians may be disabled
added: server parameter for steerable parachutes regardless of scenario (ie-- IFA, SOG)
added: server parameter for no restrictions to player parajump location (ie-- the maintarget area)
fixed: combat UAV spawned at correct altitude
added: more no-HUD
=> CUP Takistan civs, walking civs may be disabled, preemptive event tuning, etc

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/scripts/fn_afterfirednear_civ_global.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf
added: civilians move back to starting position after threaten cooldown completes (if threatened to move too far from start position)
fixed: preemptive event correctly applies adaptive group counts
=> civs move to start position

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf
fixed: explicitly unset cleanup d_do_not_delete when preemptive event ends
=> more minor fixes

co30_Domination.Altis/missions/events/fn_event_enemy_incoming.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_defend.sqf, co30_Domination.Altis/missions/events/fn_event_guerrilla_infantry_incoming.sqf, co30_Domination.Altis/server/fn_civilianmodule.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf, co30_Domination.Altis/server/fn_endmaintarget.sqf, co30_Domination.Altis/server/fn_mchelper.sqf, co30_Domination.Altis/server/fn_target_clear.sqf
fixed: preemptive event cleanup not working when persistent corpses is enabled
fixed: admin may use end maintarget function when a preemptive event is running
fixed: if guerrilla events are enabled there is a 50/50 chance for a preemptive (defense) event
=> fix preemptive cleanup bug

co30_Domination.Altis/server/fn_makemgroup.sqf
added: if enemy skill is very low, low, normal then aim/reload skills are reduced
Reduced aimingShake seems more fun, fewer players deaths but still with the fun of being attacked.  But it may be too easy for some servers... good?  no good?
=> reduced aim and reload

co30_Domination.Altis/description.ext, co30_Domination.Altis/init/fn_preinit.sqf, co30_Domination.Altis/scripts/fn_Zen_OccupyHouse.sqf, co30_Domination.Altis/scripts/fn_createsimpleobject.sqf, co30_Domination.Altis/server/fn_createmaintarget.sqf
added: support for mods - Project injury reaction (PiR) and Death and Hit Reactions (DAH)
fixed: disabling static camps was also disabling vehicles
fixed: when d_EnableSimulationCamps is set then enable damage for created objects, for example sandbag emplacements will not be invulnerable to damage
fixed: try to delete units that are hovering by checking Z axis a few times after unit is spawned
=> support for mods - Project injury reaction and Death and hit reactions

co30_Domination.Altis/server/fn_entitykilled.sqf, co30_Domination.Altis/server/fn_makevgroup.sqf
added: destroyed vehicles persist until end of target when d_ai_persistent_corpses == 0
=> persist destroyed vehicles when d_ai_persistent_corpses == 0
